# Generated by Django 2.1.5 on 2020-03-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200303_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
