# Generated by Django 3.0.4 on 2020-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200305_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal_charge_id',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
